### ISSUE TITLE
Support for arbitrary sections of information

### ISSUE THREAD

**Issue by spacez320** [waynr/pyresume#103]
I was able to successfully generate a pretty slick looking PDF resume based off the existing codebase! This is awesome!

I think my next goal personally is to be able to flesh it out with sections of information that extend beyond what the standard template gives me. Things like a "non-work projects" section or a "volunteering" section, etc.

@waynr I think there's essentially two ways of doing this ... either we make the standard template support arbitrary fields, support specific things I propose adding, or we create the ability to use custom tex templates.

I'm willing to take a go at making this happen myself and submitting a PR. I'm curious, though, which implementation you prefer, if you're ok with adding this feature in the first place?

Thanks for the previous help!

**Comment by waynr** [comment]
I like the idea of arbitrary sections, and I think the standard template should support it but I also want to keep in mind the goal of template interchangeability. This means that for probably 95% of use cases we should aim for enabling the user to easily point their resume data at different templates to see how their resume looks with different typesetting but incorporating the same information.

Because of this, I'd like to eventually transition away from the hard-coded section types to more of a widget-like approach with the following characteristics:

* the only difference between your "work" and "volunteer" experience sections in your resume would be that they would have different "name" or "title" fields which would be used to create the section headers in the tex output.
* instead of top-level dictionaries for the resume data format, we would have top-level lists where the order of the elements in the resume data determine the order of the sections of the resume.

So to more directly answer your question, I think we should add the new behavior you are suggesting to the standard template and postpone the custom tex templates until one of us has an opportunity to refactor the standard to support a widget-like approach, and I'd be happy to review a PR!

By the way, here's a nice little helper script that somewhat streamlines template work:

```
#!/usr/bin/env bash
#
# This script is intended to support development on pyresume templates and
# attributes files by automatically running pyresume whenever any file paths
# passed as parameters to this script are updated. This requires the
# "inotifywait" tool to be installed on your development system.

watch_files=${1:?}
input_files=${2:?}

build_dir=./build

xpdf -remote meow $build_dir/wayne-warren.pdf &

echo "about to watch $input_files"
while RES=$(
        inotifywait -r -e close_write \
                    $watch_files \
                    $input_files \
         ) ;do
    echo $RES
    pyresume create tex $input_files > $build_dir/wayne-warren.tex
    latexmk -outdir=$build_dir -interaction=nonstopmode -pdf $build_dir/wayne-warren.tex
    xpdf -remote meow -reload
done
```

Maybe I should just add that to the git repo...

**Comment by spacez320** [comment]
I think I know what you're saying about the widget approach. So instead of something like this:

```
--- attributes.yaml
sectionA:
  - foo
  - bar
sectionB:
  - fizz
  - buzz

--- templates/whatever.tex
{% if (sectionA is defined and sectionA|length > 0) %}
  ... something that displays sectionA ...
{% endif %}
```

... maybe it would do something like this, maybe?

```
--- attributes.yaml
two-column-widget:
  - name: sectionA
    data:
      - foo
      - bar

bullet-list-widget:
  - name: sectionB
    data:
      - fizz
      - buzz

--- templates/whatever.tex
{% for widget in widgets %}
  ... some logic that displays the widget in the order supplied in the yaml and according to the widget type ...
{% endfor %}
```

If I've got a handle on what you're suggesting, I could try playing around with this.

**Comment by waynr** [comment]
@spacez320 more like this:

```
--- attributes.yaml
- name: sectionA
  type: two-columns
  data:
    - foo
    - bar
- name: sectionB
  type: bullet-list
  data:
    - fizz
    - buzz
```

The use of a top-level list seems to me like the best way to achieve arbitrary section ordering.

If you are going to work on implementing the widget-based approach in addition to adding the sections you are originally requesting, I would prefer that you implement it as a new template type and leave the standard template alone for now -- once we see that the widget-based approach can produce essentially the same output as what the standard template currently produces, then we can go ahead and remove it.

**Comment by spacez320** [comment]
Wow, TeX is a beast.

I think I need to make sure this tests out, but a draft of the actual change: https://github.com/spacez320/pyresume/pull/1

Attached is the produced resume.

[engineering.pdf](https://github.com/waynr/pyresume/files/2130875/engineering.pdf)
